### ISSUE TITLE
Type Error thrown in ZF3

### ISSUE THREAD

**Issue by byteworksng** [zendframework/ZendDeveloperTools#225] opened 2016-07-28 16:20 UTC
I get the following error each time I brake something in my code. 

> Fatal Error: Uncaught TypeError: Argument 1 passed to ZendDeveloperTools\Exception\SerializableException::__construct() must be an instance of Exception, instance of Error given called in .../vendor/zendframework/zend-developer-tools/src/Collector/ExceptionCollector.php on line 45 and defined in .../vendor/zendframework/zend-developer-tools/src/Exception/SerializableException.php on line 26

The culprit appears to be a request for **"\Exception"** type, i worked around this by changing to **"\Throwable"** on .../vendor/zendframework/zend-developer-tools/src/Exception/SerializableException.php

**Comment by Ocramius** [comment] 2016-07-28 16:42
Dupe of https://github.com/zendframework/ZendDeveloperTools/pull/217

**Closed by Ocramius** 2016-07-28 16:42 UTC
